package golog

import (
	"testing"
	"time"
)

func TestFileLog(t *testing.T) {
	logger := New(LevelDebug, 0, 0, NewJSONEncoder(""))
	defer logger.Close()

	logger.AddWriter(Console())
	logger.Warn("DDDDDDDDDDDDDDDD")
	logger.Info("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	logger.Debug("DDDDDDDDDDDDDDDD")
	time.Sleep(100 * time.Millisecond)
}
